[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
abi_stable = "0.11.3"
wkt = { version = "0.10.0", default-features = false }
geo-types = { path = "../geo-types" }
